language: node_js

node_js:
- '8'

script:
- yarn lint
- yarn test

jobs:
  include:
  - stage: release
    node_js: '8'
    # dont run test cases again in release step
    deploy:
      provider: npm
      email: mayank1791989@gmail.com
      skip_cleanup: true
      api_key:
        secure: WbF347KXqA/4SC75XqwspFvRWqulpNWsoKj8nMZxza9ZlrN6Q+vXdCVIQmcYg9ryuMoxzBnhxi1JVkFHbKJLIfYCrsLkFirnXv7zzh0nhyPIa512gOlQTDB9wkEyt4Z9AyfzV2fz9sB7RsYtbjms4WYSFQrUdLSmhoDX7AV2kkpIFTSGjvBkZSBFuuYOk/GNaFpPfWtA6Iw/lxQF8s0OPN+6vR05TiJOW4Ie76RgL9+fDpmJ3wJ6s2iRYFbC3XEyn+vusHSNEV4bwrPBN+TsVK6J63jQGEISnjbMJYMJdVZOrkIxRkxH6S5W4c5sY5StsVTvg5GOAOmwXdSptxOl2YY6GlJRa6g3FbWdlG16tDSJAjefzf0ozgucJH0qin3U9RDQkp4xkKykLbB5FRKXbcvuG2oVVPzGlUUz+HCZCbEhQoBjQZaeIIR9vs1JL+/DpBVmg0EzYd2AGBPaFlpZ+tZQKDQU7BqwvWk3P3Bcj+BT23mvH90MBi3+RG5fncY+CDTrEnLmj8uPjZP0ZoxzimupRu6zcrkqZO63vk7Mi0zurRdhpDkguxOawgFZ8ujXZRsrX4bcVoVkMdAsgAWQqMbbLTk3Bo7RvffdEycwDvlJcvr5fs2ConPbBowlFDK0fhm0GbmkG39U5PmkomX7ZiSWY6wQ/u1sVHN2jU0Nfeg=
      on:
        tags: true
